### ISSUE TITLE
MIN macro sometimes causes conflicts with existing definitions

### ISSUE THREAD

**Issue by 0-wiz-0** [fpesce/ftwin#4]
Some system headers define a MIN() macro (if they should or not is a different question).
src/ft_file.h unconditionally (re-)defines it. This should be wrapped in a 

```
#ifndef MIN
#define MIN...
#endif
```

**Comment by fpesce** [comment]
@0-wiz-0 : does this issue still happens after 3355fd9e347457e9da2e090717532c540b065ccb ?
